// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpmbevjqewwwahxvsdqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwbWJldmpxZXd3d2FoeHZzZHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5ODU0NTYsImV4cCI6MjA1MTU2MTQ1Nn0.YId8e9PbDsdTJRgl1nfanEQCZBcP_d4l1YVlKttmXjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);